In [1]:
%load_ext autoreload
%autoreload 2
import numpy as np
import json
from cpmpy import * # pip3 install cpmpy
from cpmpy.solvers import CPM_ortools

In [2]:
# helper function to enumerate all models, for a list of key variables
# with limit
def enumerate_all(model, variables, limit=None):
    model = CPM_ortools(model) # this speeds up repeated solving
    count = 0
    while model.solve():
        print(variables.value())
        model += ~all(variables == variables.value())
        if limit is not None:
            count += 1
            if count > limit:
                break

What I think is the underlying model:

In [3]:
# returns (model, variables)
def manual_type01(size, inputData):
    v = intvar(1,size, shape=size)
    
    m = Model()
    
    # data_pairs: v[i] != v[j]
    for (s,t) in inputData:
        m += [v[s] != v[t]]
    
    # the objective
    m.maximize(max(v))

    return (m,v)

In [4]:
# lets enumerate a few
(m,v) = manual_type01(size=10, inputData=[(1,0), (5,4), (8,6)])
enumerate_all(m,v,limit=10)

[ 1  2  1  1  1  2 10  1  1  1]
[ 1 10  1  1  1  2  2  1  1  1]
[ 1  2  1  1  1  2  1  1 10  1]
[ 1  2  1  1  1  2  1  1  2 10]
[ 1  2  1  1  1  2  2  1  1 10]
[ 1  2  1  1  1  2 10  1  1  2]
[ 1  2  1  1  1  2  3  1  1 10]
[ 1  2  1  1  1  2 10  1  1  3]
[ 1  2  1  1  1  2  4  1  1 10]
[ 1  2  1  1  1  2 10  1  1  4]
[ 1  2  1  1  1  2  5  1  1 10]


In [5]:
data = json.load(open('instances/type01/instance0.json'))
# some manual work...
size = len(data['formatTemplate']['list'])
inputData = [list(dd.values()) for dd in data['inputData']['list']]
print(size, inputData)
(m,v) = manual_type01(size=size, inputData=inputData)
enumerate_all(m,v,limit=10)

10 [[1, 0], [5, 4], [8, 6]]
[ 1  2  1  1  1  2 10  1  1  1]
[ 1 10  1  1  1  2  2  1  1  1]
[ 1  2  1  1  1  2  1  1 10  1]
[ 1  2  1  1  1  2  1  1  2 10]
[ 1  2  1  1  1  2  2  1  1 10]
[ 1  2  1  1  1  2 10  1  1  2]
[ 1  2  1  1  1  2  3  1  1 10]
[ 1  2  1  1  1  2 10  1  1  3]
[ 1  2  1  1  1  2  4  1  1 10]
[ 1  2  1  1  1  2 10  1  1  4]
[ 1  2  1  1  1  2  5  1  1 10]


In [6]:
data = json.load(open('instances/type01/instance1.json'))
# some manual work...
size = len(data['formatTemplate']['list'])
inputData = [list(dd.values()) for dd in data['inputData']['list']]
print(size, inputData)
(m,v) = manual_type01(size=size, inputData=inputData)
enumerate_all(m,v,limit=10)

11 [[2, 0], [3, 0], [4, 0], [5, 0], [6, 0], [4, 1], [7, 1], [10, 1], [3, 2], [5, 2], [7, 2], [10, 2], [5, 3], [7, 3], [9, 3], [10, 3], [5, 4], [6, 4], [6, 5], [8, 7], [9, 7], [10, 7], [10, 8], [10, 9]]
[ 3  1  5  1 11  2  4  2  5  3  4]
[ 2  1 11  1  3  4  1  2  3  3  4]
[ 2  1  3  1  3 11  1  2  3  3  4]
[ 2  1  3  1  4 11  1  2  3  3  4]
[ 2  1  3  1  5 11  1  2  3  3  4]
[ 2  1  3  1  6 11  1  2  3  3  4]
[ 2  1  3  1  7 11  1  2  3  3  4]
[ 4  1 11  1  3  2  1  2  3  3  4]
[ 1 11  5  4  4  3  2  2  3  3  1]
[ 1  4  5  3  3  4  2  2  3 11  1]
[ 1 11  5  3  3  4  2  2  3  4  1]


Example checking the model
...

See Type02, but then with also the data preprocessing like above...